# Generated by Django 5.2.4 on 2025-08-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_atelier_equipement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_defaillance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('heuregen', models.DurationField(blank=True, editable=False, null=True)),
                ('methode_entretien', models.CharField(max_length=255)),
                ('nature_panne', models.CharField(max_length=255)),
                ('cause_panne', models.CharField(max_length=255)),
                ('indice_gravite', models.IntegerField()),
                ('piece_rechange', models.TextField()),
                ('travaux_effectues', models.TextField()),
                ('etat_action_immediate', models.TextField()),
                ('pilote', models.CharField(max_length=255)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='base.atelier')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='base.equipement')),
            ],
        ),
    ]
