# Generated by Django 5.2.4 on 2025-08-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formulaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('element', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
            ],
        ),
    ]
