# Generated by Django 5.2.4 on 2025-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='indice_gravite',
            field=models.CharField(max_length=255),
        ),
    ]
